apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadbhpj5077-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadbhpj5077-tenant-component
    app.kubernetes.io/part-of: loadbhpj5077-tenant-app
  name: loadbhpj5077-tenant-component
  namespace: loadbhpj5077-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadbhpj5077-tenant-component
    weight: null
status: {}
